// flow-typed signature: 497264ebb8f7c4554fb9ef6cbdd23219
// flow-typed version: <<STUB>>/babel-preset-mobx_v^2.0.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-mobx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-mobx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-mobx/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-mobx/index' {
  declare module.exports: $Exports<'babel-preset-mobx'>;
}
declare module 'babel-preset-mobx/index.js' {
  declare module.exports: $Exports<'babel-preset-mobx'>;
}
declare module 'babel-preset-mobx/lib/index' {
  declare module.exports: $Exports<'babel-preset-mobx/lib'>;
}
declare module 'babel-preset-mobx/lib/index.js' {
  declare module.exports: $Exports<'babel-preset-mobx/lib'>;
}
