// flow-typed signature: 2b1b33cb1b7b7e0af662c0d1113cefd8
// flow-typed version: <<STUB>>/jest-environment-jsdom-fourteen_v0.1.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-environment-jsdom-fourteen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-environment-jsdom-fourteen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-environment-jsdom-fourteen/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-environment-jsdom-fourteen/lib/index' {
  declare module.exports: $Exports<'jest-environment-jsdom-fourteen/lib'>;
}
declare module 'jest-environment-jsdom-fourteen/lib/index.js' {
  declare module.exports: $Exports<'jest-environment-jsdom-fourteen/lib'>;
}
