// flow-typed signature: d3c7ee39d606c50cf0ed094d33a4d1a8
// flow-typed version: <<STUB>>/mini-css-extract-plugin_v0.5.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mini-css-extract-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mini-css-extract-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mini-css-extract-plugin/dist/cjs' {
  declare module.exports: any;
}

declare module 'mini-css-extract-plugin/dist' {
  declare module.exports: any;
}

declare module 'mini-css-extract-plugin/dist/loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mini-css-extract-plugin/dist/cjs.js' {
  declare module.exports: $Exports<'mini-css-extract-plugin/dist/cjs'>;
}
declare module 'mini-css-extract-plugin/dist/index' {
  declare module.exports: $Exports<'mini-css-extract-plugin/dist'>;
}
declare module 'mini-css-extract-plugin/dist/index.js' {
  declare module.exports: $Exports<'mini-css-extract-plugin/dist'>;
}
declare module 'mini-css-extract-plugin/dist/loader.js' {
  declare module.exports: $Exports<'mini-css-extract-plugin/dist/loader'>;
}
