// flow-typed signature: c8349dec24e29e71acb8e7389f6b6979
// flow-typed version: <<STUB>>/mobx_v5.13.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx' {
  declare export {
    IObservable,
    IDepTreeNode,
    Reaction,
    IReactionPublic,
    IReactionDisposer,
    IDerivation,
    untracked,
    IDerivationState,
    IAtom,
    createAtom,
    IAction,
    spy,
    IComputedValue,
    IEqualsComparer,
    comparer,
    IEnhancer,
    IInterceptable,
    IInterceptor,
    IListenable,
    IObjectWillChange,
    IObjectDidChange,
    IObservableObject,
    isObservableObject,
    IValueDidChange,
    IValueWillChange,
    IObservableValue,
    isObservableValue as isBoxedObservable,
    IObservableArray,
    IArrayWillChange,
    IArrayWillSplice,
    IArrayChange,
    IArraySplice,
    isObservableArray,
    IKeyValueMap,
    ObservableMap,
    IMapEntries,
    IMapEntry,
    IMapWillChange,
    IMapDidChange,
    isObservableMap,
    IObservableMapInitialValues,
    ObservableSet,
    isObservableSet,
    ISetDidChange,
    ISetWillChange,
    IObservableSetInitialValues,
    transaction,
    observable,
    IObservableFactory,
    IObservableFactories,
    computed,
    IComputed,
    isObservable,
    isObservableProp,
    isComputed,
    isComputedProp,
    extendObservable,
    observe,
    intercept,
    autorun,
    IAutorunOptions,
    reaction,
    IReactionOptions,
    when,
    IWhenOptions,
    action,
    isAction,
    runInAction,
    IActionFactory,
    keys,
    values,
    entries,
    set,
    remove,
    has,
    get,
    decorate,
    configure,
    onBecomeObserved,
    onBecomeUnobserved,
    flow,
    toJS,
    trace,
    IObserverTree,
    IDependencyTree,
    getDependencyTree,
    getObserverTree,
    resetGlobalState as _resetGlobalState,
    getGlobalState as _getGlobalState,
    getDebugName,
    getAtom,
    getAdministration as _getAdministration,
    allowStateChanges as _allowStateChanges,
    allowStateChangesInsideComputed as _allowStateChangesInsideComputed,
    Lambda,
    isArrayLike,
    $mobx,
    isComputingDerivation as _isComputingDerivation,
    onReactionError,
    interceptReads as _interceptReads,
    IComputedValueOptions
  } from './internal';
}


/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobx/lib/mobx.es6' {
  declare module.exports: any;
}

declare module 'mobx/lib/mobx' {
  declare module.exports: any;
}

declare module 'mobx/lib/mobx.min' {
  declare module.exports: any;
}

declare module 'mobx/lib/mobx.module' {
  declare module.exports: any;
}

declare module 'mobx/lib/mobx.umd' {
  declare module.exports: any;
}

declare module 'mobx/lib/mobx.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobx/lib/mobx.es6.js' {
  declare module.exports: $Exports<'mobx/lib/mobx.es6'>;
}
declare module 'mobx/lib/mobx.js' {
  declare module.exports: $Exports<'mobx/lib/mobx'>;
}
declare module 'mobx/lib/mobx.min.js' {
  declare module.exports: $Exports<'mobx/lib/mobx.min'>;
}
declare module 'mobx/lib/mobx.module.js' {
  declare module.exports: $Exports<'mobx/lib/mobx.module'>;
}
declare module 'mobx/lib/mobx.umd.js' {
  declare module.exports: $Exports<'mobx/lib/mobx.umd'>;
}
declare module 'mobx/lib/mobx.umd.min.js' {
  declare module.exports: $Exports<'mobx/lib/mobx.umd.min'>;
}
