// flow-typed signature: bf1e8f9b58243a096d584083a6141e43
// flow-typed version: <<STUB>>/react-garden-kit_v0.0.1/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-garden-kit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-garden-kit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-garden-kit/src' {
  declare module.exports: any;
}

declare module 'react-garden-kit/src/lib/ctx' {
  declare module.exports: any;
}

declare module 'react-garden-kit/src/lib/defaults' {
  declare module.exports: any;
}

declare module 'react-garden-kit/src/lib/router' {
  declare module.exports: any;
}

declare module 'react-garden-kit/src/lib/service-manager' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-garden-kit/index' {
  declare module.exports: $Exports<'react-garden-kit'>;
}
declare module 'react-garden-kit/index.js' {
  declare module.exports: $Exports<'react-garden-kit'>;
}
declare module 'react-garden-kit/src/index' {
  declare module.exports: $Exports<'react-garden-kit/src'>;
}
declare module 'react-garden-kit/src/index.js' {
  declare module.exports: $Exports<'react-garden-kit/src'>;
}
declare module 'react-garden-kit/src/lib/ctx/index' {
  declare module.exports: $Exports<'react-garden-kit/src/lib/ctx'>;
}
declare module 'react-garden-kit/src/lib/ctx/index.js' {
  declare module.exports: $Exports<'react-garden-kit/src/lib/ctx'>;
}
declare module 'react-garden-kit/src/lib/defaults/index' {
  declare module.exports: $Exports<'react-garden-kit/src/lib/defaults'>;
}
declare module 'react-garden-kit/src/lib/defaults/index.js' {
  declare module.exports: $Exports<'react-garden-kit/src/lib/defaults'>;
}
declare module 'react-garden-kit/src/lib/router/index' {
  declare module.exports: $Exports<'react-garden-kit/src/lib/router'>;
}
declare module 'react-garden-kit/src/lib/router/index.js' {
  declare module.exports: $Exports<'react-garden-kit/src/lib/router'>;
}
declare module 'react-garden-kit/src/lib/service-manager/index' {
  declare module.exports: $Exports<'react-garden-kit/src/lib/service-manager'>;
}
declare module 'react-garden-kit/src/lib/service-manager/index.js' {
  declare module.exports: $Exports<'react-garden-kit/src/lib/service-manager'>;
}
