// flow-typed signature: 828b5f945b3c5087086f1e41103dbc42
// flow-typed version: <<STUB>>/react-with-firebase-auth_v^1.0.4/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-with-firebase-auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-with-firebase-auth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-with-firebase-auth/dist/index.es' {
  declare module.exports: any;
}

declare module 'react-with-firebase-auth/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-with-firebase-auth/dist/index.es.js' {
  declare module.exports: $Exports<'react-with-firebase-auth/dist/index.es'>;
}
declare module 'react-with-firebase-auth/dist/index' {
  declare module.exports: $Exports<'react-with-firebase-auth/dist'>;
}
declare module 'react-with-firebase-auth/dist/index.js' {
  declare module.exports: $Exports<'react-with-firebase-auth/dist'>;
}
